### ISSUE TITLE
CMake version/policy missmatch

### ISSUE THREAD

**Issue by erikbosch** [ihedvall/mdflib#163]
In https://github.com/ihedvall/mdflib/blob/main/CMakeLists.txt it is specified that minimum cmake version is 3.15, but it also refers to CMP0167 that was added first in cmake 3.30. This gives a compilation error if using cmake<3.30

Using something like below helps with the compilation problem, while keeping 3.15+ as required version. I have verified that compilation after that change works with cmake 3.28, but have not done any additional checking as of now.

```
cmake_minimum_required(VERSION 3.15)
cmake_policy(SET CMP0074 NEW)
cmake_policy(SET CMP0091 NEW)

if(POLICY CMP0167)
  # added in cmake 3.30
  cmake_policy(SET CMP0167 NEW)
endif()
```
